name: CloudHub - Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndDeploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Build and Deploy with Maven
      run: mvn clean -B package deploy -DmuleDeploy -s .maven/settings.xml

      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
        PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
        SANDBOX_CLIENT_ID: ${{ secrets.SANDBOX_CLIENT_ID }}
        SANDBOX_CLIENT_SECRET: ${{ secrets.SANDBOX_CLIENT_SECRET }}